INSERT INTO CABIN VALUES(1,0,'M','World Traveller');
INSERT INTO CABIN VALUES(2,20,'W','World Traveller Plus');
INSERT INTO CABIN VALUES(3,50,'J','Club World');
INSERT INTO CABIN VALUES(4,100,'F','First');
