INSERT INTO CABIN VALUES(1,0,'M','World Traveller');
INSERT INTO CABIN VALUES(2,20,'W','World Traveller Plus');
INSERT INTO CABIN VALUES(3,50,'J','Club World');
INSERT INTO CABIN VALUES(4,100,'F','First');

INSERT INTO AIRPORT VALUES(1,'LHR','London Heathrow');
INSERT INTO AIRPORT VALUES(2,'LAX','Los Angeles International');
INSERT INTO AIRPORT VALUES(3,'SFO','San Francisco International');
INSERT INTO AIRPORT VALUES(4,'JFK','John F Kennedy International');
INSERT INTO AIRPORT VALUES(5,'LGW','London Gatwick');
INSERT INTO AIRPORT VALUES(6,'YYZ','Lester B. Pearson International');

INSERT INTO ROUTE VALUES(1,4500,1,2);
INSERT INTO ROUTE VALUES(2,4500,2,1);
INSERT INTO ROUTE VALUES(3,4400,1,3);
INSERT INTO ROUTE VALUES(4,4400,3,1);
INSERT INTO ROUTE VALUES(5,3200,1,4);
INSERT INTO ROUTE VALUES(6,3200,4,1);
INSERT INTO ROUTE VALUES(7,3250,5,6);
INSERT INTO ROUTE VALUES(8,3250,6,5);
